export const MOCK_LOCATION = {
    country: 'Wonderland',
    lng: 12345,
    searchType: 'Test',
    alternative: [],
    index: 1,
    bookingId: 'ds',
    placeType: 'S' as const,
    placeKey: '123',
    iata: 'Test',
    countryIso: 'Test',
    locationId: 'Test',
    name: 'Test',
    ufi: 123,
    isPopular: true,
    region: 'Test',
    lang: 'Test',
    lat: 123,
};
