export const MOCK_LOCATIONS = [
    {
        country: 'Germany',
        lng: 11.7862,
        searchType: 'L',
        alternative: ['DE,Upper Bavaria,München'],
        index: 1,
        bookingId: 'airport-15986',
        placeType: 'A' as const,
        placeKey: '1471994',
        iata: 'MUC',
        countryIso: 'de',
        locationId: '15986',
        name: 'Munich Airport',
        ufi: 22020,
        isPopular: true,
        region: 'Bavaria',
        lang: 'en',
        lat: 48.3545,
    },
    {
        country: 'Germany',
        lng: 11.5756,
        searchType: 'L',
        alternative: ['DE,Upper Bavaria'],
        index: 2,
        bookingId: 'city-947019',
        placeType: 'C' as const,
        placeKey: '1000959742',
        countryIso: 'de',
        locationId: '9251',
        name: 'Munich',
        ufi: -1829149,
        isPopular: false,
        region: 'Bavaria',
        lang: 'en',
        lat: 48.1373,
    },
    {
        country: 'Romania',
        lng: 26.0844,
        searchType: 'L',
        alternative: ['RO,Henri Coandă'],
        index: 3,
        bookingId: 'airport-28681',
        placeType: 'A' as const,
        placeKey: '1472627',
        iata: 'OTP',
        countryIso: 'ro',
        locationId: '28681',
        name: 'Bucharest Otopeni Airport',
        ufi: 900038676,
        isPopular: true,
        region: 'Muntenia',
        lang: 'en',
        lat: 44.5725,
    },
    {
        country: 'Romania',
        lng: 26.0946,
        searchType: 'L',
        alternative: ['RO'],
        index: 4,
        bookingId: 'city-2025790',
        placeType: 'C' as const,
        placeKey: '1000960478',
        countryIso: 'ro',
        locationId: '16966',
        name: 'Bucharest',
        ufi: -1153951,
        isPopular: false,
        region: 'Muntenia',
        lang: 'en',
        lat: 44.4378,
    },
    {
        country: 'Spain',
        lng: -1.13236,
        city: 'Murcia',
        searchType: 'L',
        alternative: ['ES,San Javier'],
        index: 5,
        bookingId: 'airport-31991',
        placeType: 'A' as const,
        placeKey: '1472054',
        iata: 'RMU',
        countryIso: 'es',
        locationId: '31991',
        name: 'Murcia Airport',
        ufi: 900038889,
        isPopular: false,
        region: 'Murcia',
        lang: 'en',
        lat: 37.8066,
    },
    {
        country: 'Spain',
        lng: -1.11667,
        searchType: 'L',
        alternative: ['ES'],
        index: 6,
        bookingId: 'city-2378674',
        placeType: 'C' as const,
        placeKey: '350918',
        countryIso: 'es',
        locationId: '18271',
        name: 'Murcia',
        ufi: -393418,
        isPopular: false,
        region: 'Murcia',
        lang: 'en',
        lat: 37.9833,
    },
];
